# kettle-jem configuration file
# This file defines merge options for template files.
#
# Structure:
#   - "defaults": Default merge options for Ruby files
#   - "patterns": Glob patterns for fallback matching (evaluated in order)
#   - "files": Nested directory structure for per-file configuration
#
# The key structure under "files" mirrors the directory hierarchy.
# Individual file configs override pattern matches, which override defaults.
#
# For Ruby files, options are passed to Prism::Merge::SmartMerger.
#
# Available merge options (JSON-compatible types):
#   strategy: "skip" | "merge"
#     - "skip": Copy file as-is without merging
#     - "merge": Use AST-aware merging for Ruby files
#   preference: "template" | "destination"
#     - "template": Template nodes take precedence over destination nodes
#     - "destination": Destination nodes take precedence over template nodes
#   add_template_only_nodes: true | false
#     - true: Add nodes that exist only in template to destination
#     - false: Only merge/replace existing nodes
#   freeze_token: string (default: "kettle-dev")
#     - Token used to mark frozen sections that should not be modified
#   max_recursion_depth: number (default: Infinity)
#     - Maximum depth for recursive merging

# Default options for Ruby files with merge strategy
defaults:
  preference: "template"
  add_template_only_nodes: true
  freeze_token: "kettle-jem"

# Glob patterns evaluated in order (first match wins)
# These provide fallback for files not explicitly listed in "files"
patterns:
  - path: ".github/**/*.yml"
    strategy: skip
  - path: ".devcontainer/**"
    strategy: skip
  - path: ".git-hooks/**"
    strategy: skip
  - path: ".junie/**"
    strategy: skip
  - path: ".qlty/**"
    strategy: skip
  - path: "gemfiles/modular/erb/**"
    strategy: merge
  - path: "gemfiles/modular/mutex_m/**"
    strategy: merge
  - path: "gemfiles/modular/stringio/**"
    strategy: merge
  - path: "gemfiles/modular/x_std_libs/**"
    strategy: merge
  - path: "*.gemspec"
    strategy: merge

# Per-file configuration (nested directory structure)
# Keys are directory/file names; leaf nodes have "strategy" and optional merge options
files:
  ".aiignore":
    strategy: skip

  ".devcontainer":
    "apt-install":
      strategy: skip
    "devcontainer.json":
      strategy: skip

  ".env.local.example":
    strategy: skip

  ".envrc":
    strategy: skip

  ".git-hooks":
    "commit-msg":
      strategy: skip
    "commit-subjects-goalie.txt":
      strategy: skip
    "footer-template.erb.txt":
      strategy: skip
    "prepare-commit-msg":
      strategy: skip

  ".github":
    ".codecov.yml":
      strategy: skip
    "FUNDING.yml":
      strategy: skip
    "dependabot.yml":
      strategy: skip
    "workflows":
      "ancient.yml":
        strategy: skip
      "auto-assign.yml":
        strategy: skip
      "codeql-analysis.yml":
        strategy: skip
      "coverage.yml":
        strategy: skip
      "current.yml":
        strategy: skip
      "dep-heads.yml":
        strategy: skip
      "dependency-review.yml":
        strategy: skip
      "heads.yml":
        strategy: skip
      "jruby.yml":
        strategy: skip
      "legacy.yml":
        strategy: skip
      "license-eye.yml":
        strategy: skip
      "locked_deps.yml":
        strategy: skip
      "opencollective.yml":
        strategy: skip
      "style.yml":
        strategy: skip
      "supported.yml":
        strategy: skip
      "truffle.yml":
        strategy: skip
      "unlocked_deps.yml":
        strategy: skip
      "unsupported.yml":
        strategy: skip

  ".gitignore":
    strategy: skip

  ".gitlab-ci.yml":
    strategy: skip

  ".idea":
    ".gitignore":
      strategy: skip

  ".junie":
    "guidelines-rbs.md":
      strategy: skip
    "guidelines.md":
      strategy: skip

  ".kettle-dev.yml":
    strategy: skip

  ".licenserc.yaml":
    strategy: skip

  ".opencollective.yml":
    strategy: skip

  ".qlty":
    "qlty.toml":
      strategy: skip

  ".rspec":
    strategy: skip

  ".rubocop.yml":
    strategy: skip

  ".rubocop_rspec.yml":
    strategy: skip

  ".simplecov":
    strategy: merge

  ".tool-versions":
    strategy: skip

  ".yardignore":
    strategy: skip

  ".yardopts":
    strategy: skip

  "Appraisal.root.gemfile":
    strategy: merge

  "Appraisals":
    strategy: merge

  "CHANGELOG.md":
    strategy: skip

  "CITATION.cff":
    strategy: skip

  "CODE_OF_CONDUCT.md":
    strategy: skip

  "CONTRIBUTING.md":
    strategy: skip

  "FUNDING.md":
    strategy: skip

  "Gemfile":
    strategy: merge

  "README.md":
    strategy: skip

  "RUBOCOP.md":
    strategy: skip

  "Rakefile":
    strategy: merge

  "SECURITY.md":
    strategy: skip

  "gemfiles":
    "modular":
      "coverage.gemfile":
        strategy: merge

      "debug.gemfile":
        strategy: merge

      "documentation.gemfile":
        strategy: merge

      "optional.gemfile":
        strategy: merge

      "runtime_heads.gemfile":
        strategy: merge

      "style.gemfile":
        strategy: merge

      "templating.gemfile":
        strategy: merge

      "x_std_libs.gemfile":
        strategy: merge

      "erb":
        "r2":
          "v3.0.gemfile":
            strategy: merge
        "r2.3":
          "v4.0.gemfile":
            strategy: merge
        "r2.6":
          "v4.0.gemfile":
            strategy: merge
        "r3":
          "v4.0.gemfile":
            strategy: merge
        "r3.1":
          "v4.0.gemfile":
            strategy: merge
        "vHEAD.gemfile":
          strategy: merge

      "mutex_m":
        "r2":
          "v0.gemfile":
            strategy: merge
        "r3.3":
          "v0.gemfile":
            strategy: merge
        "vHEAD.gemfile":
          strategy: merge

      "stringio":
        "r2":
          "v3.0.gemfile":
            strategy: merge
        "r2.3":
          "v3.1.gemfile":
            strategy: merge
        "r2.7":
          "v3.1.gemfile":
            strategy: merge
        "r3":
          "v3.1.gemfile":
            strategy: merge
        "r3.1":
          "v3.1.gemfile":
            strategy: merge
        "vHEAD.gemfile":
          strategy: merge

      "x_std_libs":
        "r2":
          "v0.gemfile":
            strategy: merge
        "r3.3":
          "v0.gemfile":
            strategy: merge
        "r3.4":
          "v0.gemfile":
            strategy: merge
        "r3.5":
          "v0.gemfile":
            strategy: merge
        "vHEAD.gemfile":
          strategy: merge
